### PR TITLE
Update settings.html

### PR DESCRIPTION
**Pull request by goosehoonk**
I removed a disabled tag that prevented ads from being disabled at all.

### CODE REVIEW

**Review by WatchGamingVideos — APPROVED** [review]

**Comment by IncognitoTGT** [comment]
this works right? 
like does it actually disable ads?

**Comment by goosehoonk** [comment]
It doesn't immediately disable ads, they are on by default. But this enables people too disable them on their port.

**Comment by IncognitoTGT** [comment]
ad's are needed for IN's official deployments so if you don't want ads do this change on your own deployment

**Comment by goosehoonk** [comment]
Understood.

**Pull request closed without merging**
