### PR TITLE
Fancade

### PR DESCRIPTION
**Pull request by WatchGamingVideos**
Add fancade game to the thing

Also pls unban from discord I was 13 and I told them that and they banned me for being under 13

I was @nvd123yt

### CODE REVIEW

**Comment by IncognitoTGT** [comment]
edit g.json too

**Comment by WatchGamingVideos** [comment]
g.json doesn't matter tbh I found that out when coding my fork

> edit g.json too

If I have too I'll open a new PR

**Comment by IncognitoTGT** [comment]
> Also pls unban from discord I was 13 and I told them that and they banned me for being under 13

You're also a skiddy skid skid

**Comment by IncognitoTGT** [comment]
> g.json doesn't matter tbh I found that out when coding my fork
> 
> > edit g.json too
> 
> If I have too I'll open a new PR

it's to make stuff easier
also just do it on this pr

**Comment by WatchGamingVideos** [comment]
Wait verify me on the repo

Ik it sounds fu*kin absurd but I can add all these apps, edit g.json, and add more tools without having to wait @IncognitoTGT

**Comment by WatchGamingVideos** [comment]
> > Also pls unban from discord I was 13 and I told them that and they banned me for being under 13
> 
> You're also a skiddy skid skid

what is a skiddy skid skid?
I dont understand brainrot

**Comment by IncognitoTGT** [comment]
> Wait verify me on the repo
> 
> Ik it sounds fu*kin absurd but I can add all these apps, edit g.json, and add more tools without having to wait @IncognitoTGT

Just do it on this PR
g.json and .min.json not being in sync causes issues

**Comment by WatchGamingVideos** [comment]
Like I rlly wanna be unbanned too because I cotribute to the repo (not saying I'm doing it to be unbanned I really just like doing it) but I also really enjoyed chatting there

**Comment by IncognitoTGT** [comment]
:yawning_face: talk to the mods dirctly

also gh  is NOT the place to ask for this

**Comment by WatchGamingVideos** [comment]
> 🥱 talk to the mods dirctly
> 
> also gh is NOT the place to ask for this

they blacklisted me from appeals
How am I supposed to do that. Can u do it for me and later (because my lunch is almost over) I'll make more commits and stuff

**Comment by WatchGamingVideos** [comment]
Also pls merge the PR already lol

**Review by IncognitoTGT — APPROVED** [review]
finally

**Pull request merged**
