### PR TITLE
Added multi-server config options

### PR DESCRIPTION
**Pull request by BenRogozinski**
Adding more servers and automatically picking the nearest one to users would make the proxy a lot faster. I added the necessary things to config.js and made a helper script to automatically get the nearest server to the user but I can't seem to figure out how to actually make it change the active Bare server. It's all run on the client side so users' privacy is not violated. Any help would be greatly appreciated.

### CODE REVIEW

**Comment by IncognitoTGT** [comment]
looks good to me

Interstellar's gonna switch to wisp for uv but bare will still be used for dynamic, so we'll need that too later on then.

**Comment by IncognitoTGT** [comment]
ignore the last comment;

Bare servers can be easily censored, so it's best if it's on the same domain as the proxy itself, which could still be possible...

BUT

Interstellar is likely moving away from bare soon, and moving to wisp, but this is probably still possible

also, how is the bare servers set in the uv config?

**Comment by BenRogozinski** [comment]
It looks like the actual UV script s load the config in multiple different places but since the code for it is minified it's very hard to track down or make the right changes to it.

This could also likely be changed to work with wisp in the future

**Review by IncognitoTGT — CHANGES_REQUESTED** [review]
A bare switcher is easy to add to UV, make the appropriate changes first before i review

**Comment by BenRogozinski** [comment]
Alright, on it!

**Comment by Riftriot** [comment]
I did this for nebula. https://github.com/NebulaServices/Nebula/blob/main/src/pages/Home.tsx
It's mostly a trival thing and just goes off speed. You don't need to list the coordinates of the server lol. It can be trivally implemented with wisp

**Comment by Riftriot** [comment]
> It looks like the actual UV script s load the config in multiple different places but since the code for it is minified it's very hard to track down or make the right changes to it.
> 
> This could also likely be changed to work with wisp in the future

UV automatically produces sourcemaps for this very reason (although it might've changed when I changed UV to use esbuild?). Not sure but it should be easy enough to enable and track down what you're looking for

**Comment by BenRogozinski** [comment]
Yeah that looks easy enough to add. And it IS easier to just switch the server based on latency but you don't always get the same latency under a higher load like with watching videos or cloud gaming. I'll probably change it to work with both methods.

**Pull request closed without merging**
