### PR TITLE
Minor css fixes and more

### PR DESCRIPTION
**Pull request by 3kh0**
Redo of #773

### CODE REVIEW

**Comment by IncognitoTGT** [comment]
update TOS css

**Comment by IncognitoTGT** [comment]
whar
image

**Comment by 3kh0** [comment]
dwhar, let me take a look

**Review by IncognitoTGT — APPROVED** [review]
rizz

**Comment by IncognitoTGT** [comment]
yeah i squashed it so it's harder to get on the leader board 🚎

**Comment by 3kh0** [comment]
f0b

**Comment by As90909wwu** [comment]
what is happening

**Pull request merged**
