### PR TITLE
Revamp ToS and Privacy policy & more

### PR DESCRIPTION
**Pull request by 3kh0**
This pull request:
- Adds Privacy policy
- Adds Terms of service
- Changed the password deny screen to the nginx default (better for hiding)
- Fixed wonky font sizes in the theme creator

### CODE REVIEW

**Comment by genericness** [comment]
i wouldn't really classify it as an improvement as this is a generic termly generated privacy policy / tos, it's not related towards IN or what it does at all

maybe write it manually instead of generating it or improve the current one?

**Review by IncognitoTGT — CHANGES_REQUESTED** [review]
Make the TOS not some generic bs

https://github.com/UseInterstellar/Interstellar/assets/72108630/4e2dc660-489e-4389-8371-ae9c7d01db09

**Review by genericness — CHANGES_REQUESTED** [review]
i wouldn't really classify it as an improvement as this is a generic termly generated privacy policy / tos, it's not related towards IN or what it does at all

maybe write it manually instead of generating it or improve the current one?

**Comment by IncognitoTGT** [comment]
Also as @genericness said make the privacy policy more pertaining towards IN

TOS is a big downgrade as it removes a lot of the stuff that the old TOS sanctioned

**Comment by genericness** [comment]
> i wouldn't really classify it as an improvement as this is a generic termly generated privacy policy / tos, it's not related towards IN or what it does at all
> 
> maybe write it manually instead of generating it or improve the current one?

to provide more information towards this, it would probably be better for the maintainers to do this anyway as termly has built in features to check for stuff like CCPA and GDPR compliance built in

**Review by IncognitoTGT — APPROVED** [review]
only the css im gutting this TOS

**Comment by IncognitoTGT** [comment]
@3kh0 can you make a new PR with the OLD tos and use a placeholder text for the privacy policy?

also allow edits by maintainers so that i can merge that into a diff branch

**Pull request closed without merging**
